### ISSUE TITLE
pusher issue?

### ISSUE THREAD

**Issue by mgkimsal** [LlmLaraHub/llmlarahub#8]
Uncaught You must pass your app key when you instantiate Pusher.

I'm not a reverb or pusher expert, and don't have any idea what I should be putting where to get this repo to work.

Any info is appreciated.  Thanks.

**Comment by alnutile** [comment]
Oh the .env.example should get you going
It is just a reverb install so some default keys should work 

```

REVERB_HOST="localhost"
REVERB_PORT=8080
REVERB_SCHEME=http

BROADCAST_CONNECTION=reverb

REVERB_APP_ID=Iepheik4Ah
REVERB_APP_KEY=ush8Etah2da9deehei4a
REVERB_APP_SECRET=zaeShae9Shoh3quie7th

VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
```

**Comment by alnutile** [comment]
I added to the example
docs coming this week
